name: Run Telegram Bot

on:
  schedule:
    # - cron: "0 * * * *" # 每小时运行一次（UTC 时间）
    - cron: "0 0 * * *" # 每天 UTC 0 时 0 分运行

  workflow_dispatch: # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make executable
        run: chmod +x telegram_bot # 确保可执行文件有执行权限

      - name: Delay for 20 seconds
        run: sleep 20

      - name: Run Telegram bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./telegram_bot
