name: Run IP Check Manually

on:
  workflow_dispatch: # 允许手动触发

jobs:
  run-ip-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make ip_check executable
        run: chmod +x ip_check/ip_check/ip_check

      - name: Run IP Check
        run: ip_check/ip_check/ip_check
